spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=schema
    username: postgres
    password: 45fofevi
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
    initialization-mode: always
    continue-on-error: true
    schema: classpath:init/schema.sql
    data: classpath:init/data.sql




